module.exports = [
  {
    id: 1,
    lastModified: new Date('8/5/2018'),
    lastModifier: '',
    content: 'apples',
    pickDate: new Date('8/5/2018'),
    lastFarmerName: 'srulik',
    status: 0,
  },
  {
    id: 2,
    lastModified: new Date('8/5/2018'),
    lastModifier: '',
    content: 'cucumbers',
    pickDate: new Date('8/4/2018'),
    lastFarmerName: 'srulik',
    status: 0,
  },
  {
    id: 3,
    lastModified: new Date('8/4/2018'),
    lastModifier: '',
    content: 'apples',
    pickDate: new Date('8/4/2018'),
    lastFarmerName: 'srulik',
    status: 1,
  },
  {
    id: 4,
    lastModified: new Date('8/4/2018'),
    lastModifier: '',
    content: 'oranges',
    pickDate: new Date('8/4/2018'),
    lastFarmerName: 'srulik',
    status: 6
  },
  {
    id: 5,
    lastModified: new Date('8/4/2018'),
    lastModifier: '',
    content: 'avocado',
    pickDate: new Date('8/4/2018'),
    lastFarmerName: 'srulik',
    status: 0,
  },
  {
    id: 12,
    lastModified: new Date('8/1/2018'),
    lastModifier: '',
    content: 'corn',
    pickDate: new Date('8/1/2018'),
    lastFarmerName: 'srulik',
    status: 8,
  },
  {
    id: 33,
    lastModified: new Date('8/5/2018'),
    lastModifier: '',
    content: 'apples',
    pickDate: new Date('8/5/2018'),
    lastFarmerName: 'srulik',
    status: 6,
  },
  {
    id: 333,
    lastModified: new Date('8/4/2018'),
    lastModifier: '',
    content: 'apples',
    pickDate: new Date('8/4/2018'),
    lastFarmerName: 'srulik',
    status: 1
  },
];
